const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const Module = require('node:module');
const compiled = ts.transpileModule(fs.readFileSync('lib/technicals.ts', 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText;
const moduleUnderTest = new Module('technicals'); moduleUnderTest._compile(compiled, 'technicals.cjs');
const { calculateTechnicals } = moduleUnderTest.exports;
const obs = Array.from({ length: 100 }, (_, i) => ({ date: new Date(Date.UTC(2025, 0, i + 1)).toISOString().slice(0, 10), value: i + 1 }));
const near = (a, b) => assert.ok(Math.abs(a - b) < 1e-8, `${a} != ${b}`);
const result = kind => calculateTechnicals(obs, kind);
assert.equal(result('rsi')[13].rsi, null); assert.equal(result('rsi')[14].rsi, 100);
assert.equal(calculateTechnicals(obs.map(p => ({ ...p, value: -p.value })), 'rsi')[99].rsi, 0);
assert.equal(calculateTechnicals(obs.map(p => ({ ...p, value: 5 })), 'rsi')[99].rsi, 50);
near(result('ma')[19].ma20, 10.5); near(result('ma')[59].ma60, 30.5);
const bands = result('bollinger')[19]; near(bands.upper, 10.5 + 2 * Math.sqrt(33.25)); near(bands.lower, 10.5 - 2 * Math.sqrt(33.25));
assert.equal(result('macd')[24].macd, null); near(result('macd')[25].macd, 700); assert.equal(result('macd')[32].signal, null); near(result('macd')[33].signal, 700); near(result('macd')[33].histogram, 0);
near(result('zscore')[59].zscore, 29.5 / Math.sqrt((60 ** 2 - 1) / 12));
const momentum = result('momentum')[20]; near(momentum.momentum1, 100); near(momentum.momentum5, 500); near(momentum.momentum20, 2000);
assert.equal(result('volatility')[19].volatility, null); near(result('volatility')[20].volatility, 0);
const uneven = obs.map((p, i) => ({ ...p, value: i * i / 100 })); near(calculateTechnicals(uneven, 'volatility')[20].volatility, Math.sqrt(140));
near(result('percentile')[99].percentile, 99.5);
near(calculateTechnicals(obs.map(p => ({ ...p, value: 5 })), 'percentile')[99].percentile, 50);
const yearly = [{ date: '2023-01-01', value: 100 }, { date: '2025-01-01', value: 1 }, { date: '2025-02-01', value: 2 }]; near(calculateTechnicals(yearly, 'percentile')[2].percentile, 75);
assert.deepEqual(calculateTechnicals([...obs].reverse(), 'ma'), result('ma'));
console.log('Technical calculations: all assertions passed');
